# Sudo used for custom apt setup
sudo: true

# Manually install ghc and cabal
before_install:
  - sudo rm /bin/sh
  - sudo ln -s /bin/bash /bin/sh
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-head
  - travis_retry curl https://ghc-artifacts.s3.amazonaws.com/nightly/validate-x86_64-linux/latest/bindist.tar.xz --output latest.tar.xz
  - tar xpvf latest.tar.xz
  - cd ghc-*
  - ./configure 
  - sudo make V=1 install
  - cd ..
  - curl https://sh.rustup.rs -sSf | sudo sh -s -- -y
  - export PATH=/usr/local/bin:/opt/cabal/head/bin:~/.cargo/bin:$PATH

# Build the project and test suite 
install:
  - echo $PATH
  - which ld
  - ld --version
  - cabal --version
  - ghc --version
  - rustc --version
  - cargo --version
  - cabal new-update
  - cabal new-build --enable-tests --allow-newer

script:
  - cabal new-test --allow-newer
