# Sudo used for custom apt setup
sudo: true

matrix:
  include:
    - os: osx
      env:
        - CABAL_TAR='https://www.haskell.org/cabal/release/cabal-install-2.2.0.0/cabal-install-2.2.0.0-x86_64-apple-darwin-sierra.tar.gz'
        - GHC_TAR='https://ghc-artifacts.s3.amazonaws.com/nightly/validate-x86_64-darwin/latest/bindist.tar.xz'
    - os: linux 
      env:
        - CABAL_TAR='https://www.haskell.org/cabal/release/cabal-install-2.2.0.0/cabal-install-2.2.0.0-x86_64-unknown-linux.tar.gz'
        - GHC_TAR='https://ghc-artifacts.s3.amazonaws.com/nightly/validate-x86_64-linux/latest/bindist.tar.xz'

# Manually install cabal-install, GHC, and rustup
before_install:
  - travis_retry curl $CABAL_TAR --output cabal.tar.xz
  - tar xpvf cabal.tar.xz
  - sudo cp cabal /usr/local/bin

  - travis_retry curl $GHC_TAR --output ghc.tar.xz
  - mkdir ghc
  - tar xpf ghc.tar.xz --strip-components 1 -C ghc
  - cd ghc
  - ./configure --disable-ld-override
  - sudo make V=1 install
  - cd ..

  - curl https://sh.rustup.rs -sSf | sudo sh -s -- -y
  - export PATH=/usr/local/bin:~/.cargo/bin:$PATH

# Build the project and test suite 
install:
  - echo $PATH
  - which ld
  - cabal --version
  - ghc --version
  - rustc --version
  - cargo --version
  - cabal new-update
  - cabal new-build --enable-tests --allow-newer

script:
  - cabal new-test --allow-newer
  - for f in examples/*.hs ; do cabal new-exec ghc -- -threaded -package inline-rust $f ; done
